### ISSUE TITLE
Unable to receive the email.

### ISSUE THREAD

**Issue by mmaniaque** [Le0Developer/cloudflare-discord-mailing#1]
Hello,

I have followed your steps to make the system work properly but despite all I do not receive any email on Discord and the bot does not seem to be online.

I have activated the Workers logs but no POST request is issued from Discord except when I configure the INTERACTIONS ENDPOINT URL.

When I try to send an email it says this.

250 2.1.0 Ok
RCPT TO:<m****@*****.**r>
550 5.1.1 Address does not exist. QShDcDofayOU
0.82s
SMTP ERROR: RCPT TO command failed: 550 5.1.1 Address does not exist. QShDcDofayOU

Sincerely
![Fe3gQMlqS1TGMZSSdauEm](https://user-images.githubusercontent.com/12367033/223932364-c536e13d-10e4-4529-ba6f-0f7eca58de12.png)
![GyGtyK25rHUeYL3DyOWLX](https://user-images.githubusercontent.com/12367033/223932366-a998b1b0-98a3-4077-8a22-46e46829e3df.png)

**Comment by Le0Developer** [comment]
> 250 2.1.0 Ok
RCPT TO:<m****@*****.**r>
550 5.1.1 Address does not exist. QShDcDofayOU
0.82s
SMTP ERROR: RCPT TO command failed: 550 5.1.1 Address does not exist. QShDcDofayOU

This sounds like an issue with Email Routing, not this project in particular.
IIRC you can disable and re-enable catch-all to fix it.
If that does not help, you should try asking in the [#email-routing channel](https://discord.gg/cloudflaredev)

> and the bot does not seem to be online.

HTTP bots don't have an active gateway connection and will never appear to be online.
